#!/usr/bin/env bash

# The input (a pair of raw fastq files generated by the sequencer on a paired-end sequencing run) will be read from the directory given by the first argument.
raw_read_dir="${1}"

pear_out_prefix="${raw_read_dir}"/pear_out

merged_reads="${pear_out_prefix}".assembled.fastq

raw_reads=($( find "${raw_read_dir}" -type f -name '*.fastq*' ))

n_threads=$( getconf _NPROCESSORS_ONLN )

pear \
    --forward-fastq "${raw_reads[0]}" \
    --reverse-fastq "${raw_reads[1]}" \
    --output "${pear_out_prefix}" \
    --threads $n_threads

exit

#---- Other Options
    -v $MINOVERLAP \
    -m $ASSMAX \
    -n $ASSMIN \
    -t $TRIMMIN \
    -q $Quality_Threshold \
    -u $UNCALLEDMAX \
    -g $TEST \
    -p $PVALUE \
    -s $SCORING \

