#!/usr/bin/env bash

# This is a shell script to cluster a fasta file of sequences into OTUs using usearch.
# works for usearch v8.0.1623_i86osx32
# It requires one and only one argument: The absolute path to a fasta file to be clustered.
# This file should contain only unique sequences - no duplicates.

# example usage: bash cluster_usearch.sh "/Users/threeprime/Desktop/Analysis_20150727_0004/all_lib/no_duplicates.fasta"

# "${1}" is the first argument
infile="${1}"

# percent similarity within which two sequences will be clustered into an OTU
cluster_radius=1

# define output files (these will be in the same directory as the infile)
dir_out="${infile%/*}"/OTUs_usearch
mkdir "${dir_out}"
out_fasta="${dir_out}"/OTUs.fasta
out_fasta_linebreak="${dir_out}"/OTUs_linebreaks.fasta
logfile="${dir_out}"/OTUs.log
out_uc="${dir_out}"/OTUs.uc

# this will automatically find the number of cores on a Unix/Linux computer
n_cores=$(getconf _NPROCESSORS_ONLN)

# write logfile
exec > >(tee "${logfile}") 2>&1

# execute usearch
usearch \
	-cluster_otus "${infile}" \
	-otu_radius_pct "${cluster_radius}" \
	-sizein \
	-sizeout \
	-relabel OTU_ \
	-otus "${out_fasta_linebreak}" \
	-uparseout "${out_uc}"

	
echo $(date +%H:%M) "Removing line breaks within fasta sequences generated by usearch (awk)..."
awk '/^>/{print (NR==1)?$0:"\n"$0;next}{printf "%s", $0}END{print ""}' "${out_fasta_linebreak}" > "${out_fasta}"
rm "${out_fasta_linebreak}"

DUPS_TO_OTUS="${dir_out}"/dups_to_otus.csv
awk -F'[\t;]' 'BEGIN{ print "Query,Match" } { if ($4 == "otu") {print $1 "," $1} else if ($4 == "match") { print $1 "," $7 } else if ($4 == "chimera") { print $1 "," "chimera"} }' "${UPARSE_OUT}" > "${DUPS_TO_OTUS}"

exit



	